services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
    volumes:
      - "./app:/app"
    environment:
      - FLASK_APP=/app/identidock.py
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identidock.rule=Host(`monster.localhost`)"
      - "traefik.http.services.identidock.loadbalancer.server.port=5000" 
  
  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "8080:8080"
    networks:
      - identinet

  redis:
    image: redis
    networks:
      - identinet

  traefik:
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
      - "--entrypoints.web.address=:81"
    ports:
      - "81:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  identinet:
