services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
    volumes:
      - "./app:/app"
    environment:
      - FLASK_APP=/app/identidock.py
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0
  
  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "8080:8080"
    networks:
      - identinet

  redis:
    image: redis
    networks:
      - identinet

networks:
  identinet:
